
#region  PALETTE
 
function ui_col(_name) {
    switch (_name) {
        case "text":    return make_colour_rgb(201, 209, 217);
        case "dim":     return make_colour_rgb(122, 133, 148);
        case "faint":   return make_colour_rgb(74,  83,  97);
        case "rule":    return make_colour_rgb(38,  44,  57);
        case "you":     return make_colour_rgb(217, 164, 65);
        case "ally":    return make_colour_rgb(78,  201, 168);
        case "war":     return make_colour_rgb(209, 91,  91);
        case "quantum": return make_colour_rgb(154, 127, 209);
    }
    return c_white;
}
 
#endregion
 
 
#region  FONT ROLES
 
// ---- FONT ASSIGNMENT -- READ THIS ----------------------------------
//
// fnt_body is currently Jersey 10 at SIZE 20, which has a line height of
// 29px. That is roughly twice what a 640x360 canvas can afford: five
// roster rows plus a header need ~180px of the 360 available, which is
// why only two kingdoms were visible and the panels collided.
//
// I cannot fix that from outside the IDE -- a GameMaker font asset bakes
// its glyph bitmaps and metrics into the .yy and .png, so editing the
// "size" field by hand would leave 20px glyphs with a 10px label on them.
// It has to be regenerated by the IDE.
//
// So as a WORKING STOPGAP, every in-game role points at fnt_label, which
// is already Jersey 10 at size 10 (line height 14) with correct glyphs.
// The project runs correctly as-is.
//
// THE PROPER FIX, 30 seconds in the IDE:
//   1. open fnt_body, set Size to 10, apply
//   2. change UI_FONT_BODY below back to fnt_body
//   3. optionally make fnt_display Jersey 10 at 20 for panel headings
//
// Jacquard 12 stays on fnt_title only, for the ending card. It is a
// Victorian needlepoint blackletter -- gorgeous, and at in-game sizes
// genuinely hard to read, as the kingdom-name heading showed. Use it
// where text is read once and slowly, not where it is scanned.
//
#macro UI_FONT_TITLE   fnt_title      // Jacquard 12 @ 36 -- endings only
#macro UI_FONT_TITLE_2 fnt_title_2      // Jacquard 12 @ 36 -- endings only
#macro UI_FONT_DISPLAY fnt_label      // -> fnt_display once resized
#macro UI_FONT_BODY    fnt_label      // -> fnt_body once resized to 10
#macro UI_FONT_LABEL   fnt_label      // Jersey 10 @ 10
 
/// Always set a font before drawing. Inherited font state is a classic
/// source of "why is this suddenly huge".
function ui_font(_role) {
    switch (_role) {
        case "title":   draw_set_font(UI_FONT_TITLE);   break;
		case "title_2":   draw_set_font(UI_FONT_TITLE_2);   break;
        case "display": draw_set_font(UI_FONT_DISPLAY); break;
        case "label":   draw_set_font(UI_FONT_LABEL);   break;
        default:        draw_set_font(UI_FONT_BODY);    break;
    }
}
 
function ui_line_h() {
    return string_height("Ay") + 2;
}
 
/// Column unit based on the WIDEST likely digit, not "0" -- in a
/// proportional font sizing a column by a narrow glyph means content
/// overruns it.
function ui_cw() {
    return string_width("8");
}
 
function ui_digits_are_tabular() {
    var _w = string_width("0");
    return (string_width("1") == _w) && (string_width("8") == _w);
}
 
#endregion
 
 
#region  LAYOUT
 
/// Allocate the screen from the actual font metrics. Returns a struct of
/// rectangles. Call once per draw, after setting the body font.
///
/// The council bar and top bar get exactly what one or two lines need;
/// the roster gets header + N rows; the CHRONICLE GETS EVERYTHING LEFT
/// OVER, because in a text-driven game the log is the game and it should
/// absorb the slack rather than being squeezed to a fixed 64px.
function ui_layout(_rows) {
    var _lh = ui_line_h();   // TEXT inside each panel still measures the
                              // real font height -- that's what stops
                              // lines overflowing. Only the panel FRAMES
                              // below are now fixed, to match the art.

    return {
        lh: _lh,
        margin: 12,
        top:     { x: 12,  y: 6,   w: 616, h: 20 },
        roster:  { x: 12,  y: 34,  w: 381, h: 104 },
        detail:  { x: 401, y: 34,  w: 227, h: 104 },
        chron:   { x: 12,  y: 146, w: 380, h: 158 },
        oaths:   { x: 401, y: 146, w: 227, h: 158 },
        council: { x: 12,  y: 312, w: 616, h: 42 },
        chron_lines: floor(158 / _lh)
    };
}
 
/// A panel is a rect plus a cursor. A single dim rule reads as structure
/// without the visual noise of a full border.
function ui_panel(_x, _y, _w, _h, _title = "") {
    draw_set_colour(ui_col("rule"));
    draw_line(_x, _y, _x + _w, _y);
 
    var _cursor = _y + 3;
    if (_title != "") {
        ui_font("label");
        ui_text(_x, _cursor, _title, ui_col("faint"), _w);
        _cursor += string_height("Ay") + 1;
        ui_font("body");
    }
    return {
        x: _x, y: _y, w: _w, h: _h,
        cursor: _cursor,
        inner_w: _w,
        bottom: _y + _h
    };
}
 
/// Accepts a rect struct from ui_layout, so callers never repeat numbers.
function ui_panel_r(_rect, _title = "") {
    return ui_panel(_rect.x, _rect.y, _rect.w, _rect.h, _title);
}

/// @desc Take space off the bottom of a panel so content cannot use it.
///
/// Call this immediately after ui_panel / ui_panel_r on any panel that will
/// draw a footer, and BEFORE any ui_para or ui_row. The whole overlap class of
/// bug comes from footers being drawn into space that content was allowed to
/// fill, and this is the only way to make that structurally impossible rather
/// than a thing you have to remember per call site.
///
/// Returns the panel so it can be chained.
function ui_reserve(_p, _amount) {
    _p.bottom -= _amount;
    return _p;
}
 
/// @desc Where a reserved footer belongs. Use this instead of
/// `_p.bottom - LH`, which is now wrong by exactly the reserved amount.
function ui_footer_y(_p) {
    return _p.bottom + 2;
}
 
function ui_room(_p) {
    return _p.bottom - _p.cursor;
}
 
#endregion
 
 
#region  TEXT PRIMITIVES THAT RESPECT BOUNDS
 
function ui_fit(_str, _maxw) {
    var _s = string(_str);
    if (string_width(_s) <= _maxw) return _s;
    var _room = _maxw - string_width("...");
    if (_room <= 0) return "";
    while (string_length(_s) > 0 && string_width(_s) > _room) {
        _s = string_copy(_s, 1, string_length(_s) - 1);
    }
    return _s + "...";
}
 
function ui_text(_x, _y, _str, _col, _maxw = 100000) {
    draw_set_halign(fa_left);
    draw_set_valign(fa_top);
    draw_set_colour(_col);
    draw_text(_x, _y, ui_fit(_str, _maxw));
}
 
/// Right-aligned. _xright is the RIGHT edge. Use for every numeric
/// column: both project fonts are proportional, so a left-aligned column
/// of 9 / 11 / 15 will not line up.
function ui_num(_xright, _y, _value, _col) {
    draw_set_halign(fa_right);
    draw_set_valign(fa_top);
    draw_set_colour(_col);
    draw_text(_xright, _y, string(_value));
    draw_set_halign(fa_left);
}

/// Right-aligned STRING. _xright is the RIGHT edge. Same idea as ui_num,
/// just for text instead of a bare value.
function ui_text_right(_xright, _y, _str, _col) {
    draw_set_halign(fa_right);
    draw_set_valign(fa_top);
    draw_set_colour(_col);
    draw_text(_xright, _y, string(_str));
    draw_set_halign(fa_left);
}

function ui_wrap(_str, _maxw) {
    var _s = string(_str);
    var _lines = [];
    var _cur = "";
    var _word = "";
 
    // manual tokeniser rather than string_split, for runtime compatibility
    for (var i = 1; i <= string_length(_s) + 1; i++) {
        var _ch = (i <= string_length(_s)) ? string_char_at(_s, i) : " ";
        if (_ch != " ") { _word += _ch; continue; }
        if (_word == "") continue;
 
        var _try = (_cur == "") ? _word : _cur + " " + _word;
        if (string_width(_try) <= _maxw) {
            _cur = _try;
        } else {
            if (_cur != "") array_push(_lines, _cur);
            _cur = (string_width(_word) > _maxw) ? ui_fit(_word, _maxw) : _word;
        }
        _word = "";
    }
    if (_cur != "") array_push(_lines, _cur);
    return _lines;
}
 
#endregion
 
 
#region  WIDGETS
 
/// Wrapped, bounded paragraph.
function ui_para(_p, _str, _col) {
    var _lh = ui_line_h();
    var _lines = ui_wrap(_str, _p.inner_w);
    for (var i = 0; i < array_length(_lines); i++) {
        if (ui_room(_p) < _lh) break;
        ui_text(_p.x, _p.cursor, _lines[i], _col, _p.inner_w);
        _p.cursor += _lh;
    }
}
 
/// The log. Newest first, wrapped to the panel, and it STOPS when it runs
/// out of vertical room rather than drawing past the panel edge. Whole
/// entries only -- half an entry reads as a rendering glitch.
function ui_log(_p, _lines) {
    var _lh = ui_line_h();
    var _first = true;
 
    for (var i = array_length(_lines) - 1; i >= 0; i--) {
        var _wrapped = ui_wrap(_lines[i], _p.inner_w);
        if (array_length(_wrapped) * _lh > ui_room(_p)) break;
 
        var _col = _first ? ui_col("text") : ui_col("dim");
        for (var j = 0; j < array_length(_wrapped); j++) {
            ui_text(_p.x, _p.cursor, _wrapped[j], _col, _p.inner_w);
            _p.cursor += _lh;
        }
        _p.cursor += 2;
        _first = false;
    }
}
 
/// Label/value row with a MEASURED label column, not an assumed one.
function ui_row(_p, _label, _value, _vcol) {
    var _lh = ui_line_h();
    if (ui_room(_p) < _lh) return;
    var _lw = string_width("standing") + string_width("  ");
    ui_text(_p.x, _p.cursor, _label, ui_col("faint"), _lw);
    ui_text(_p.x + _lw, _p.cursor, _value, _vcol, _p.inner_w - _lw);
    _p.cursor += _lh;
}
 
function ui_meter(_x, _y, _w, _frac, _col) {
    _frac = clamp(_frac, 0, 1);
    draw_set_colour(ui_col("rule"));
    draw_rectangle(_x, _y, _x + _w, _y + 2, false);
    if (_frac > 0) {
        draw_set_colour(_col);
        draw_rectangle(_x, _y, _x + _w * _frac, _y + 2, false);
    }
}
 
#endregion